//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaperDetail
    {
        public int PaperID { get; set; }
        public int QuestionID { get; set; }
        public int SortCode { get; set; }
    
        public virtual Paper Paper { get; set; }
        public virtual Question Question { get; set; }
    }
}
