//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Question()
        {
            this.Answers = new HashSet<Answer>();
            this.PaperDetails = new HashSet<PaperDetail>();
            this.StuQueRecordDetails = new HashSet<StuQueRecordDetail>();
        }
    
        public int QuestionID { get; set; }
        public string QuestionTitle { get; set; }
        public bool QuestionType { get; set; }
        public int QuestionLevel { get; set; }
        public int BookID { get; set; }
        public int ChapterID { get; set; }
        public bool IsCheck { get; set; }
        public int CreatorID { get; set; }
        public System.DateTime CreateTime { get; set; }
        public Nullable<int> CheckID { get; set; }
        public Nullable<System.DateTime> CheckTime { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Shan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Answer> Answers { get; set; }
        public virtual Chapter Chapter { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaperDetail> PaperDetails { get; set; }
        public virtual TextBook TextBook { get; set; }
        public virtual Teacher Teacher { get; set; }
        public virtual Teacher Teacher1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StuQueRecordDetail> StuQueRecordDetails { get; set; }
    }
}
