//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RuleDetail
    {
        public int DetailID { get; set; }
        public int RuleID { get; set; }
        public int BookID { get; set; }
        public Nullable<int> ChapterID { get; set; }
        public int QuestionCount { get; set; }
        public int QuestionLevel { get; set; }
        public Nullable<bool> Shan { get; set; }
    
        public virtual Chapter Chapter { get; set; }
        public virtual PaperRule PaperRule { get; set; }
        public virtual TextBook TextBook { get; set; }
    }
}
